
package com.onndoo.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorWebServiceImplService", targetNamespace = "http://ws.onndoo.com/", wsdlLocation = "http://localhost:8002/testservice/calculatorWebService?wsdl")
public class CalculatorWebServiceImplService
    extends Service
{

    private final static URL CALCULATORWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATORWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.onndoo.com/", "CalculatorWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/testservice/calculatorWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATORWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CalculatorWebServiceImplService() {
        super(__getWsdlLocation(), CALCULATORWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorWebServiceImpl
     */
    @WebEndpoint(name = "CalculatorWebServiceImplPort")
    public CalculatorWebServiceImpl getCalculatorWebServiceImplPort() {
        return super.getPort(new QName("http://ws.onndoo.com/", "CalculatorWebServiceImplPort"), CalculatorWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorWebServiceImpl
     */
    @WebEndpoint(name = "CalculatorWebServiceImplPort")
    public CalculatorWebServiceImpl getCalculatorWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.onndoo.com/", "CalculatorWebServiceImplPort"), CalculatorWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATORWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CALCULATORWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
